name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
    uses: zavestudios/platform-pipelines/.github/workflows/hugo-build.yml@c0159f042136961310d5dce6ebe780805f7e9781

  deploy:
    name: Deploy Hugo Site
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: zavestudios/platform-pipelines/.github/workflows/hugo-deploy.yml@c0159f042136961310d5dce6ebe780805f7e9781

  link-check:
    name: Check Markdown Links
    uses: zavestudios/platform-pipelines/.github/workflows/link-check.yml@c0159f042136961310d5dce6ebe780805f7e9781
